"""
Abstract BaseLLM interface for AURORA.

This class defines the unified API for any language model backend (OpenAI API, local HuggingFace model, or other providers).

Every backend must expose:

    generate(prompt: str, max_tokens: int = 1024) -> str

This returns the raw string generated by the model.
"""

from abc import ABC, abstractmethod


class BaseLLM(ABC):

    @abstractmethod
    def generate(self, prompt: str, max_tokens: int = 1024) -> str:
        """
        Generate text from the model.

        Parameters
        ----------
        prompt : str
            The input prompt given to the model.
        max_tokens : int
            Maximum number of tokens to generate.

        Returns
        -------
        str :
            Raw string produced by the model.
        """
        raise NotImplementedError
