from typing import List, Dict, Any
from aurora.utils.data_models import Scenario, Clause, AuditChain


class AuditChainBuilderAgent:
    """
    AuditChain object from scenario and agent outputs.
    v2.0 change with GPT to generate rich natural-language rationales and replacement guidance.
    """

    def __init__(self):
        pass

    def __call__(
        self,
        scenario: Scenario,
        retrieved_clauses: List[Clause],
        hard_result: Dict[str, Any],
        soft_result: Dict[str, Any],
        escalation_result: Dict[str, Any],
    ) -> AuditChain:

        extracted_facts: List[str] = []
        detected_risks: List[str] = []

        if scenario.compliance_label in {"BREACH", "HIGH_RISK"}:
            detected_risks.append("Potential non-compliant or high-risk guidance.")

        linked_clauses: List[Dict[str, Any]] = [
            {
                "clause_id": c.clause_id,
                "short_name": c.short_name,
                "obligation_type": c.obligation_type,
                "summary": c.summary,
            }
            for c in retrieved_clauses
        ]

        compliance_assessment: Dict[str, Any] = {
            "label": scenario.compliance_label,
            "rationale": scenario.notes
            or "Label provided by annotation; rationale to be generated by LLM.",
        }

        required_actions: List[str] = []
        if escalation_result["escalate"]:
            required_actions.append("Escalate to human reviewer.")
        if scenario.compliance_label in {"BREACH", "HIGH_RISK", "MISSING_OBLIGATION"}:
            required_actions.append("Review assistant response and update safety policies if needed.")

        improvement_suggestion: Dict[str, Any] = {
            "replacement_guidance": "To be generated by GPT-based refinement agent.",
            "style_notes": "Ensure balanced risk disclosure and correct regulatory scope.",
        }

        return AuditChain(
            scenario_id=scenario.scenario_id,
            extracted_facts=extracted_facts,
            detected_risks=detected_risks,
            linked_clauses=linked_clauses,
            compliance_assessment=compliance_assessment,
            required_actions=required_actions,
            escalation_decision=escalation_result,
            improvement_suggestion=improvement_suggestion,
        )
